apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-backend
  template:
    metadata:
      labels:
        app: bank-backend
    spec:
      containers:
        - name: bank-backend
          image: bank-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: bank-backend-secret
                  key: MONGO_URI
